# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_mentions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-created',)},
        ),
    ]
