# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(validators=[quotes.models.WordCountValidator(min_count=2)]),
        ),
    ]
