# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import quotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(validators=[quotes.models.WordCountValidator(min_count=2)], verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='title'),
        ),
    ]
